name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'emanuele-toma/axios-tor'
    steps:
      - name: Enable squash and merge for Dependabot PRs
        run: gh pr merge --squash --subject "$PR_TITLE" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Publish Package to npmjs
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "publish-to-npm.yml",
              ref: "main"
            });
            core.info(`Triggered Publish Package to npmjs workflow: ${response.status}`);